[build-system]
requires = ["setuptools>=70"]
build-backend = "setuptools.build_meta"

[project]
name = "ligotools"
version = "0.1.0"
description = "Python library for tools used in LIGO gravitational wave detection tutorial"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [{ name = "Ligo Scientific Collaboration (LSC) and Yujian Zhou", email = "yujian_zhou@berkeley.edu" }]

dependencies = [
  "numpy==2.0.*",
  "scipy==1.13.*",
  "h5py==3.12.*",
  "matplotlib==3.9.*",
  "ipykernel==6.29.*"
]

[project.urls]
Homepage = "https://github.com/UCB-stat-159-f25/hw3-zyj1151"
Issues   = "https://github.com/UCB-stat-159-f25/hw3-zyj1151/issues"


[tool.setuptools.packages.find]
where = ["."]
include = ["ligotools*"]
